version: '3.3'
services:
 springboatapp:
   environment:
   - MONGO_DB_HOSTNAME=mongo
   - MONGO_DB_USERNAME=devdb
   - MONGO_DB_PASSWORD=devdb1234
   environment:
   - MONGO_INITDB_ROOT_USERNAME=devdb 
   - MONGO_INITDB_ROOT_PASSWORD=devdb1234

  


